from __future__ import annotations

import httpx
import pytest
from fastapi import Depends, FastAPI
from pydantic import ValidationError

from fastapi_mvt.auth import Auth
from fastapi_mvt.auth.passwords import check_password, make_password, needs_rehash
from fastapi_mvt.db import model_schema
from tests.models import Account, Post

SECRET = "test-secret-key-that-is-long-enough-0123456789"


# ── Schemas ─────────────────────────────────────────────────────────────────


def test_model_schema_modes():
    read = model_schema(Post)
    create = model_schema(Post, "create")
    update = model_schema(Post, "update")

    assert {"id", "created_at", "updated_at", "title"} <= set(read.model_fields)
    assert "id" not in create.model_fields and "created_at" not in create.model_fields
    assert create.model_fields["title"].is_required()
    assert not create.model_fields["views"].is_required()
    assert create.model_fields["views"].default == 0
    assert not any(f.is_required() for f in update.model_fields.values())

    with pytest.raises(ValidationError, match="200"):
        create(title="x" * 201, author_id=1)
    # Regression: timestamps must be parsed into datetimes, not passed through as strings.
    parsed = read(**{**dict.fromkeys(read.model_fields), "id": 1, "title": "t", "views": 0, "author_id": 1,
                     "created_at": "2026-01-01T10:00:00+00:00", "updated_at": "2026-01-01T10:00:00Z"})
    assert parsed.created_at.year == 2026 and parsed.created_at.tzinfo is not None


def test_columns_with_database_defaults_are_optional_not_hidden():
    from tests.models import Course

    create = model_schema(Course, "create")
    assert "level" in create.model_fields and not create.model_fields["level"].is_required()


def test_private_columns_never_appear():
    for mode in ("read", "create", "update"):
        fields = model_schema(Account, mode).model_fields
        assert "password" not in fields and "token_version" not in fields


# ── Passwords ───────────────────────────────────────────────────────────────


def test_password_hashes_are_django_compatible():
    encoded = make_password("s3cret", iterations=1000)
    assert encoded.startswith("pbkdf2_sha256$1000$")
    assert check_password("s3cret", encoded)
    assert not check_password("wrong", encoded)
    assert needs_rehash(encoded)
    # Generated by Django 5.2 (django.contrib.auth.hashers.make_password("django-password")):
    django_hash = "pbkdf2_sha256$1000000$3oVOwZR128kdn60p1RyQT4$aHc9glllE1p2SH1MS6h8CWWDlwHlbhZ0eosvBLoNWe0="
    assert check_password("django-password", django_hash)
    assert not check_password("anything", "!")


# ── Auth flow ───────────────────────────────────────────────────────────────


@pytest.fixture
async def auth_client(db):
    auth = Auth(Account, secret_key=SECRET)
    app = FastAPI()
    db.init_app(app)
    app.include_router(auth.router)

    @app.get("/admin-only")
    async def admin_only(user=Depends(auth.superuser)):
        return {"ok": True}

    @app.get("/maybe")
    async def maybe(user=Depends(auth.optional_user)):
        return {"user": user.email if user else None}

    async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://t") as c:
        c.auth_obj = auth  # type: ignore[attr-defined]
        yield c


def bearer(token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {token}"}


async def register_and_login(c, email="Ada@Example.com", password="correct-horse"):
    r = await c.post("/auth/register", json={"email": email, "password": password})
    assert r.status_code == 201, r.text
    r = await c.post("/auth/login", json={"email": email, "password": password})
    assert r.status_code == 200, r.text
    return r.json()


async def test_register_login_me(auth_client):
    tokens = await register_and_login(auth_client)
    me = await auth_client.get("/auth/me", headers=bearer(tokens["access_token"]))
    assert me.status_code == 200
    body = me.json()
    assert body["email"] == "ada@example.com"  # normalised
    assert "password" not in body and "token_version" not in body
    account = await Account.objects.get(email="ada@example.com")
    assert account.password.startswith("pbkdf2_sha256$") and account.last_login is not None


async def test_duplicate_and_invalid_registration(auth_client):
    await register_and_login(auth_client)
    r = await auth_client.post("/auth/register", json={"email": "ada@example.com", "password": "another-pass"})
    assert r.status_code == 409
    assert (await auth_client.post("/auth/register", json={"email": "bad", "password": "long-enough"})).status_code == 422
    assert (await auth_client.post("/auth/register", json={"email": "b@x.io", "password": "short"})).status_code == 422


async def test_wrong_credentials_and_bad_tokens(auth_client):
    await register_and_login(auth_client)
    r = await auth_client.post("/auth/login", json={"email": "ada@example.com", "password": "nope-nope"})
    assert r.status_code == 401
    r = await auth_client.post("/auth/login", json={"email": "ghost@example.com", "password": "nope-nope"})
    assert r.status_code == 401
    assert (await auth_client.get("/auth/me")).status_code == 401
    assert (await auth_client.get("/auth/me", headers=bearer("garbage"))).status_code == 401


async def test_swagger_form_login(auth_client):
    await register_and_login(auth_client)
    r = await auth_client.post("/auth/token", data={"username": "ada@example.com", "password": "correct-horse"})
    assert r.status_code == 200 and r.json()["token_type"] == "bearer"


async def test_refresh_and_token_types(auth_client):
    tokens = await register_and_login(auth_client)
    # A refresh token is not an access token and vice versa.
    assert (await auth_client.get("/auth/me", headers=bearer(tokens["refresh_token"]))).status_code == 401
    r = await auth_client.post("/auth/refresh", json={"refresh_token": tokens["access_token"]})
    assert r.status_code == 401
    r = await auth_client.post("/auth/refresh", json={"refresh_token": tokens["refresh_token"]})
    assert r.status_code == 200
    assert (await auth_client.get("/auth/me", headers=bearer(r.json()["access_token"]))).status_code == 200


async def test_logout_revokes_every_token(auth_client):
    tokens = await register_and_login(auth_client)
    headers = bearer(tokens["access_token"])
    assert (await auth_client.post("/auth/logout", headers=headers)).status_code == 204
    assert (await auth_client.get("/auth/me", headers=headers)).status_code == 401
    r = await auth_client.post("/auth/refresh", json={"refresh_token": tokens["refresh_token"]})
    assert r.status_code == 401


async def test_change_password(auth_client):
    tokens = await register_and_login(auth_client)
    headers = bearer(tokens["access_token"])
    r = await auth_client.post("/auth/password", json={"current_password": "wrong", "new_password": "new-password-1"}, headers=headers)
    assert r.status_code == 400
    r = await auth_client.post(
        "/auth/password", json={"current_password": "correct-horse", "new_password": "new-password-1"}, headers=headers
    )
    assert r.status_code == 204
    assert (await auth_client.get("/auth/me", headers=headers)).status_code == 401
    await register_and_login_existing(auth_client, "ada@example.com", "new-password-1")


async def register_and_login_existing(c, email, password):
    r = await c.post("/auth/login", json={"email": email, "password": password})
    assert r.status_code == 200


async def test_inactive_users_and_superuser_guard(auth_client):
    tokens = await register_and_login(auth_client)
    headers = bearer(tokens["access_token"])
    assert (await auth_client.get("/admin-only", headers=headers)).status_code == 403
    assert (await auth_client.get("/maybe")).json() == {"user": None}
    assert (await auth_client.get("/maybe", headers=headers)).json() == {"user": "ada@example.com"}

    await Account.objects.filter(email="ada@example.com").update(is_active=False)
    assert (await auth_client.get("/auth/me", headers=headers)).status_code == 401
    r = await auth_client.post("/auth/login", json={"email": "ada@example.com", "password": "correct-horse"})
    assert r.status_code == 401


def test_auth_rejects_weak_secrets():
    with pytest.raises(ValueError, match="32 characters"):
        Auth(Account, secret_key="change-me")
    with pytest.raises(TypeError, match="AbstractUser"):
        Auth(Post, secret_key=SECRET)


async def test_lockout_after_repeated_failures(db):
    auth = Auth(Account, secret_key=SECRET, max_failed_logins=3, lockout_minutes=15)
    app = FastAPI()
    db.init_app(app)
    app.include_router(auth.router)
    async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://t") as c:
        await register_and_login(c)
        wrong = {"email": "ada@example.com", "password": "wrong-password"}
        assert [(await c.post("/auth/login", json=wrong)).status_code for _ in range(3)] == [401, 401, 401]
        # Locked now: even the right password is refused, and the counter was committed despite the 401s.
        locked = await c.post("/auth/login", json={"email": "ada@example.com", "password": "correct-horse"})
        assert locked.status_code == 429 and "Retry-After" in locked.headers
        account = await Account.objects.get(email="ada@example.com")
        assert account.locked_until is not None

        await Account.objects.filter(id=account.id).update(locked_until=None)
        ok = await c.post("/auth/login", json={"email": "ada@example.com", "password": "correct-horse"})
        assert ok.status_code == 200


async def test_password_reset_flow(db):
    sent: list[str] = []

    async def send(user, token):
        sent.append(token)

    auth = Auth(Account, secret_key=SECRET, send_password_reset=send)
    app = FastAPI()
    db.init_app(app)
    app.include_router(auth.router)
    async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://t") as c:
        tokens = await register_and_login(c)
        unknown = await c.post("/auth/password-reset", json={"email": "nobody@example.com"})
        known = await c.post("/auth/password-reset", json={"email": "ada@example.com"})
        assert unknown.status_code == known.status_code == 202
        assert unknown.json() == known.json()  # doesn't reveal which emails exist
        assert len(sent) == 1

        confirm = {"token": sent[0], "new_password": "brand-new-password"}
        assert (await c.post("/auth/password-reset/confirm", json=confirm)).status_code == 204
        assert (await c.post("/auth/password-reset/confirm", json=confirm)).status_code == 400  # single use
        assert (await c.get("/auth/me", headers=bearer(tokens["access_token"]))).status_code == 401  # old tokens revoked
        await register_and_login_existing(c, "ada@example.com", "brand-new-password")
        bad = {"token": "not-a-token", "new_password": "whatever-123"}
        assert (await c.post("/auth/password-reset/confirm", json=bad)).status_code == 400


def test_reset_endpoints_only_when_a_sender_is_configured():
    paths = {route.path for route in Auth(Account, secret_key=SECRET).router.routes}
    assert "/auth/password-reset" not in paths
