"""Django-style migration commands, implemented on Alembic.

These functions contain the logic; ``fastapi_mvt.cli`` only prints.
"""

from __future__ import annotations

import asyncio
import contextlib
import io
import shutil
import tempfile
import uuid
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Optional

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import Script, ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected, CommandError

from fastapi_mvt.migrations.autogen import MigrationAborted, Prompter, RevisionHook, RevisionPlan, revision_id
from fastapi_mvt.project import ProjectConfig, load_database, load_project_models

TEMPLATES = Path(__file__).parent / "templates"


class MigrationError(Exception):
    """A migration command cannot proceed; the message tells the user what to do."""


@dataclass
class MigrationState:
    revision: str
    doc: str
    applied: bool
    path: str


# ── Setup ───────────────────────────────────────────────────────────────────


def ensure_migrations_dir(project: ProjectConfig) -> bool:
    """Create ``migrations/`` if needed. Returns True when it was created."""
    path = project.migrations_path
    created = not path.exists()
    (path / "versions").mkdir(parents=True, exist_ok=True)
    for name in ("env.py", "script.py.mako", "README"):
        target = path / name
        if not target.exists():
            shutil.copyfile(TEMPLATES / name, target)
    env = (path / "env.py").read_text(encoding="utf-8")
    if "run_migrations" not in env:
        raise MigrationError(
            f"{path / 'env.py'} was not generated by fastapi-mvt. Replace its contents with:\n\n"
            + (TEMPLATES / "env.py").read_text(encoding="utf-8")
        )
    return created


def alembic_config(project: ProjectConfig, database: Any = None, *, stdout: Any = None) -> Config:
    cfg = Config(stdout=stdout or io.StringIO(), output_buffer=io.StringIO())
    cfg.set_main_option("script_location", str(project.migrations_path))
    cfg.set_main_option("file_template", "%%(rev)s")
    cfg.attributes["project"] = project
    cfg.attributes["database"] = database or load_database(project)
    return cfg


def _script(cfg: Config) -> ScriptDirectory:
    return ScriptDirectory.from_config(cfg)


def _run_on_connection(database: Any, fn: Callable[[Any], Any]) -> Any:
    async def main() -> Any:
        try:
            async with database.engine.connect() as conn:
                return await conn.run_sync(fn)
        finally:
            await database.dispose()

    return asyncio.run(main())


def current_heads(cfg: Config) -> tuple[str, ...]:
    database = cfg.attributes["database"]
    return tuple(_run_on_connection(database, lambda conn: MigrationContext.configure(conn).get_current_heads()))


def _all_revisions(script: ScriptDirectory) -> list[Script]:
    """Base -> head order."""
    return list(reversed(list(script.walk_revisions())))


def _applied(script: ScriptDirectory, heads: tuple[str, ...]) -> set[str]:
    applied: set[str] = set()
    for head in heads:
        for rev in script.iterate_revisions(head, "base"):
            applied.add(rev.revision)
    return applied


def _next_number(script: ScriptDirectory) -> int:
    numbers = []
    revisions = _all_revisions(script)
    for rev in revisions:
        prefix = rev.revision.split("_", 1)[0]
        if prefix.isdigit():
            numbers.append(int(prefix))
    return (max(numbers) if numbers else len(revisions)) + 1


def _single_head(script: ScriptDirectory) -> Optional[str]:
    heads = script.get_heads()
    if len(heads) > 1:
        raise MigrationError(
            "Conflicting migrations detected; multiple leaf migrations: "
            + ", ".join(sorted(heads))
            + ".\nThis happens when two branches both added migrations. Run `makemigrations --merge`."
        )
    return heads[0] if heads else None


def resolve_revision(script: ScriptDirectory, target: str) -> str:
    """Accept a full id, a unique prefix such as ``0003``, ``zero`` or ``head``."""
    if target in ("zero", "base"):
        return "base"
    if target in ("head", "heads", "latest"):
        return _single_head(script) or "base"
    matches = [r.revision for r in _all_revisions(script) if r.revision == target or r.revision.startswith(target)]
    if not matches:
        raise MigrationError(f"No migration matches {target!r}. See `showmigrations`.")
    if len(matches) > 1 and target not in matches:
        raise MigrationError(f"{target!r} is ambiguous: {', '.join(matches)}")
    return target if target in matches else matches[0]


def _script_path(result: Any) -> str:
    """The file path of the Script alembic returned (it may return a list, or None)."""
    script = result[0] if isinstance(result, list) else result
    if script is None:
        raise MigrationError("Alembic did not write a migration file.")
    return str(script.path)


def _relative(project: ProjectConfig, path: str) -> str:
    try:
        return str(Path(path).resolve().relative_to(project.root)).replace("\\", "/")
    except ValueError:
        return path


# ── Commands ────────────────────────────────────────────────────────────────


@dataclass
class MakeMigrationsResult:
    plan: RevisionPlan
    path: Optional[str]
    created_directory: bool


@contextlib.contextmanager
def scratch_database(project: ProjectConfig) -> Iterator[tuple[Any, Optional[str]]]:
    """A throwaway database of the project's kind: ``(database or None, reason if None)``.

    makemigrations builds it from the migration history and compares the models
    against it, like Django compares against migration files: your development
    database's state (pending migrations, manual changes) doesn't matter.
    """
    from sqlalchemy.pool import NullPool

    from fastapi_mvt.db import Database

    live = load_database(project)  # loaded first, so it stays the default Database
    backend = live.url.get_backend_name()
    if backend == "sqlite":
        directory = tempfile.mkdtemp(prefix="fastapi_mvt_")
        scratch = Database(
            f"sqlite+aiosqlite:///{Path(directory, 'scratch.sqlite3').as_posix()}", default=False, poolclass=NullPool
        )
        try:
            yield scratch, None
        finally:
            asyncio.run(scratch.dispose())
            shutil.rmtree(directory, ignore_errors=True)
        return
    if backend == "postgresql":
        name = f"{(live.url.database or 'db')[:40]}_mvt_scratch_{uuid.uuid4().hex[:8]}"
        admin = live.url.set(database="postgres")
        try:
            asyncio.run(_admin_execute(admin, f'CREATE DATABASE "{name}"'))
        except Exception as exc:
            yield None, f"could not create a scratch database ({type(exc).__name__}: {exc})"
            return
        scratch = Database(live.url.set(database=name), default=False, poolclass=NullPool)
        try:
            yield scratch, None
        finally:
            asyncio.run(scratch.dispose())
            try:
                asyncio.run(_admin_execute(admin, f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
            except Exception:
                pass
        return
    yield None, f"scratch databases are not supported for {backend}"


async def _admin_execute(url: Any, statement: str) -> None:
    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(url, isolation_level="AUTOCOMMIT")
    try:
        async with engine.connect() as conn:
            await conn.execute(text(statement))
    finally:
        await engine.dispose()


def _build_from_history(project: ProjectConfig, scratch: Any, has_migrations: bool) -> Config:
    cfg = alembic_config(project, database=scratch)
    if has_migrations:
        try:
            with contextlib.redirect_stdout(io.StringIO()):
                command.upgrade(cfg, "heads")
        except Exception as exc:
            raise MigrationError(
                f"Your existing migrations fail on a fresh database: {type(exc).__name__}: {exc}\n"
                "Fix the failing migration file first."
            ) from exc
    return cfg


def makemigrations(
    project: ProjectConfig,
    *,
    name: Optional[str] = None,
    empty: bool = False,
    allow_destructive: bool = False,
    prompter: Optional[Prompter] = None,
) -> MakeMigrationsResult:
    created_directory = ensure_migrations_dir(project)
    load_project_models(project)
    live_cfg = alembic_config(project)
    script = _script(live_cfg)
    head = _single_head(script)
    plan = RevisionPlan(
        number=_next_number(script),
        is_initial=head is None,
        name=name,
        empty=empty,
        allow_destructive=allow_destructive,
    )

    if empty:
        rev_id = revision_id(plan.number, name or "auto")
        with contextlib.redirect_stdout(io.StringIO()):
            result = command.revision(live_cfg, message=(name or "auto").replace("_", " "), rev_id=rev_id)
        plan.revision = rev_id
        return MakeMigrationsResult(plan, _relative(project, _script_path(result)), created_directory)

    with scratch_database(project) as (scratch, reason):
        if scratch is not None:
            cfg = _build_from_history(project, scratch, head is not None)
            plan.row_counts_known = False  # a scratch database has no rows: ask, like Django
        else:
            cfg = live_cfg
            plan.warnings.append(f"Compared against your database instead: {reason}.")
            applied = current_heads(cfg)
            if head is not None and set(applied) != {head}:
                pending = [r.revision for r in _all_revisions(script) if r.revision not in _applied(script, applied)]
                raise MigrationError(
                    f"Your database has {len(pending)} unapplied migration(s): {', '.join(pending)}.\n"
                    "Run `migrate` first, so makemigrations compares your models with an up-to-date database."
                )
        cfg.attributes["process_revision_directives"] = RevisionHook(plan, prompter or Prompter(interactive=False))
        try:
            with contextlib.redirect_stdout(io.StringIO()):
                result = command.revision(cfg, message=name or "auto", autogenerate=True, rev_id="pending")
        except MigrationAborted:
            raise
        except CommandError as exc:
            raise MigrationError(str(exc)) from exc
    if plan.no_changes or not result:
        plan.no_changes = True
        return MakeMigrationsResult(plan, None, created_directory)
    return MakeMigrationsResult(plan, _relative(project, _script_path(result)), created_directory)


def merge(project: ProjectConfig) -> Optional[str]:
    ensure_migrations_dir(project)
    cfg = alembic_config(project)
    script = _script(cfg)
    heads = script.get_heads()
    if len(heads) < 2:
        return None
    rev_id = revision_id(_next_number(script), "merge_" + "_".join(h.split("_", 1)[0] for h in sorted(heads)))
    with contextlib.redirect_stdout(io.StringIO()):
        result = command.merge(cfg, "heads", message="merge", rev_id=rev_id)
    return _relative(project, _script_path(result))


@dataclass
class MigrateResult:
    applied: list[str]
    unapplied: list[str]
    model_changes_pending: bool


def migrate(
    project: ProjectConfig,
    target: Optional[str] = None,
    *,
    on_step: Optional[Callable[[str, bool], None]] = None,
    check_models: bool = True,
) -> MigrateResult:
    ensure_migrations_dir(project)
    cfg = alembic_config(project)
    script = _script(cfg)
    if not _all_revisions(script):
        raise MigrationError("There are no migrations yet. Run `makemigrations` first.")

    destination = resolve_revision(script, target or "head")
    heads = current_heads(cfg)
    applied = _applied(script, heads)
    result = MigrateResult([], [], False)

    def record(ctx: Any, step: Any, heads: Any, run_args: Any) -> None:
        revision = step.up_revision_id
        (result.applied if step.is_upgrade else result.unapplied).append(revision)
        if on_step:
            on_step(revision, step.is_upgrade)

    cfg.attributes["on_version_apply"] = record
    if destination == "base" or (destination in applied and destination not in heads):
        command.downgrade(cfg, destination)
    elif destination not in heads:
        command.upgrade(cfg, destination)

    if check_models and (target is None or destination == script.get_current_head()):
        # The database is at head now, so compare with it directly: no scratch
        # database is ever created on the server you deploy to.
        result.model_changes_pending = has_unmigrated_changes(project, against_history=False)
    return result


def has_unmigrated_changes(project: ProjectConfig, *, against_history: bool = True) -> bool:
    """True if the models differ from what the migrations produce."""
    load_project_models(project)
    if against_history:
        with scratch_database(project) as (scratch, _reason):
            if scratch is not None:
                has_migrations = bool(_all_revisions(_script(alembic_config(project))))
                return _diff_detected(_build_from_history(project, scratch, has_migrations))
    return _diff_detected(alembic_config(project))


def _diff_detected(cfg: Config) -> bool:
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected:
        return True
    except CommandError:
        return False
    return False


def rollback(project: ProjectConfig, steps: int = 1, *, on_step: Optional[Callable[[str, bool], None]] = None) -> list[str]:
    cfg = alembic_config(project)
    script = _script(cfg)
    heads = current_heads(cfg)
    if not heads:
        raise MigrationError("No migrations are applied; nothing to roll back.")
    if len(heads) > 1:
        raise MigrationError("The database has multiple heads; use `migrate <revision>` to choose a target.")
    chain = [r.revision for r in script.iterate_revisions(heads[0], "base")]
    target = chain[steps] if steps < len(chain) else "base"
    return migrate(project, target if target != "base" else "zero", on_step=on_step, check_models=False).unapplied


def showmigrations(project: ProjectConfig) -> list[MigrationState]:
    ensure_migrations_dir(project)
    cfg = alembic_config(project)
    script = _script(cfg)
    applied = _applied(script, current_heads(cfg))
    return [
        MigrationState(r.revision, r.doc or "", r.revision in applied, _relative(project, r.path))
        for r in _all_revisions(script)
    ]


def sqlmigrate(project: ProjectConfig, target: str, *, backwards: bool = False) -> str:
    cfg = alembic_config(project)
    script = _script(cfg)
    revision = resolve_revision(script, target)
    if revision == "base":
        raise MigrationError("Name a migration, e.g. `sqlmigrate 0002`.")
    down = script.get_revision(revision).down_revision
    previous = down if isinstance(down, str) else (down[0] if down else "base")
    try:
        if backwards:
            command.downgrade(cfg, f"{revision}:{previous}", sql=True)
        else:
            command.upgrade(cfg, f"{previous}:{revision}" if previous != "base" else revision, sql=True)
    except Exception as exc:
        if cfg.attributes["database"].is_sqlite:
            raise MigrationError(
                f"Could not render SQL offline ({exc}). SQLite migrations use batch mode, which needs a "
                "live database; set DATABASE_URL to a PostgreSQL URL to preview its SQL."
            ) from exc
        raise
    buffer: Any = cfg.output_buffer
    return str(buffer.getvalue())
